Modal input change
solidtop/esc-hacker-escape-rooms pull request #24
Opened 2022-12-13 11:40 UTC by solidtop

Participants select ändrad till en simpel input (type=number) i modal menyn. 
input är begränsad med min/max och har attributen "required" satt till true som visar meddelande om du överskrider begränsningarna. Säg till om det är något jag missat :)

Inkluderar även js bundles så det funkar på pages!

![input type number](https://user-images.githubusercontent.com/107689239/207308089-3158c2dc-caf2-46d2-bef4-b0fe6d582aa5.png)

2022-12-13 22:51 UTC, JonathanHolmgren approved these changes
Bra jobbat, testat och funkar bra!

2022-12-15 11:18 UTC, matodorovic approved these changes
Testat och fungerar som det ska. 👍

2022-12-15 11:20 UTC, matodorovic requested changes
Du har en merge konflikt här. Kanske mergea in nya main till din branch och kör webpack igen?

2022-12-15 12:25 UTC, merged

2022-12-15 12:28 UTC, matodorovic reviewed
Great!